CREATE TABLE
  t_gs_usuario (
    email VARCHAR(255) NOT NULL UNIQUE,
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL
  );

CREATE TABLE
  t_gs_tipo_dispositivo (
    consumo_medio NUMBER (7, 2),
    id_tipo_dispositivo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL UNIQUE
  );

CREATE TABLE
  t_gs_estimativa_consumo (
    consumo_medio NUMBER (7, 2) NOT NULL,
    frequencia_uso_medio VARCHAR(255) NOT NULL,
    id_estimativa_consumo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    t_gs_tipo_dispositivo_id_tipo_dispositivo INTEGER NOT NULL,
    t_gs_usuario_id_usuario INTEGER NOT NULL,
    uso_medio NUMBER (4, 1) NOT NULL,
    FOREIGN KEY (t_gs_tipo_dispositivo_id_tipo_dispositivo) REFERENCES t_gs_tipo_dispositivo (id_tipo_dispositivo),
    FOREIGN KEY (t_gs_usuario_id_usuario) REFERENCES t_gs_usuario (id_usuario)
  );

CREATE TABLE
  t_gs_sugestao_economia (
    descricao VARCHAR(1000) NOT NULL,
    id_sugestao_economia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    t_gs_usuario_id_usuario INTEGER NOT NULL,
    FOREIGN KEY (t_gs_usuario_id_usuario) REFERENCES t_gs_usuario (id_usuario)
  );
  
  
  
-- Selects das tabelas
SELECT * FROM  t_gs_usuario;
SELECT * FROM  t_gs_tipo_dispositivo;
SELECT * FROM  t_gs_estimativa_consumo;
SELECT * FROM  t_gs_sugestao_economia;


-- DROPS das tabelas
DROP TABLE t_gs_usuario;
DROP TABLE t_gs_tipo_dispositivo;
DROP TABLE t_gs_estimativa_consumo;
DROP TABLE t_gs_sugestao_economia;




